[[custom_nodes]]
node_id = "ComfyUI-WanVideoWrapper"
version = "latest"

[[custom_nodes]]
node_id = "ComfyUI-MelBandRoFormer"
version = "latest"

[[custom_nodes]]
node_id = "comfyui-kjnodes"
version = "latest"

[[custom_nodes]]
node_id = "comfyui-videohelpersuite"
version = "latest"
